spring:
  datasource:
#    url: jdbc:mysql://10.25.183.251:3306/yhjc_act?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=true
#    username: yhjc
#    password: yhjc@#root
    url: jdbc:mysql://localhost:3306/activitidb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    #1.flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    #2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    #3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    #4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true
    #检测历史表是否存在 activiti7默认没有开启数据库历史记录 启动数据库历史记录
    db-history-used: true
    #记录历史等级 可配置的历史级别有none, activity, audit, full
    # none: 不保存任何的历史数据，在流程执行过程中 最高效
    # activity: 级别高于 none 保存流程实例与流程行为，其他的数据不保存
    # audit: 除activity 级别保存的数据外，还会保存全部的流程任务及其属性，默认为此类型
    # full: 最高级别，audit 级别保存的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等
    history-level: full
    #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false

server:
  port: 19001
  servlet:
    application-display-name: activity-servre
    #文件大小设置
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yanghu.manage
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: uuid
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: true  #二级缓存关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置项分组
my:
  # 文件上传路径配置
  fileUpload:
    # 流程文件存储根路径
    flow: E:/flowFiles/